// Runs at build time (wired as `predev`/`prebuild` in package.json) — the
// ONLY thing that decides WHEN images get fetched. Calls getCategoryImages
// once per real category, for BOTH verticals, and writes the results to
// src/data/categoryPhotos.generated.ts (Furniture) and
// src/data/dwCategoryPhotos.generated.ts (Doors & Windows), which frontend
// pages import directly as plain static data.
//
// Also fetches admin-created (dynamic) categories — see
// api-lib/dynamicCategories.ts for why they're stored in Cloudinary rather
// than committed into shared/furnitureCategories.ts /
// shared/doorsWindowsCategories.ts — and writes them to
// src/data/dynamicCategories.generated.ts, AND merges them into the
// category list looped over below, so a newly-created category's Cloudinary
// folder gets scanned for photos exactly like every static category's does.
//
// Resilient by design: a category the client hasn't uploaded to yet, a
// network hiccup, or missing credentials on a fresh local clone should
// never fail the whole build — they just produce an empty array for that
// category, and the existing hasValue/placeholder pattern takes it from
// there.
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getCategoryImages, type CategoryPhoto } from "./imageProvider.ts";
import { furnitureCategories } from "../shared/furnitureCategories.ts";
import { doorsWindowsCategories } from "../shared/doorsWindowsCategories.ts";
import { getDynamicCategories, type DynamicCategory } from "../api-lib/dynamicCategories.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const hasCredentials =
  !!process.env.VITE_CLOUDINARY_CLOUD_NAME &&
  !!process.env.CLOUDINARY_API_KEY &&
  !!process.env.CLOUDINARY_API_SECRET;

interface GenerateOptions {
  label: string; // for console logging only
  categories: readonly { id: string }[];
  outPath: string;
  varName: string; // e.g. "categoryPhotosByCategory"
}

async function generate(opts: GenerateOptions): Promise<void> {
  const result: Record<string, CategoryPhoto[]> = {};

  for (const cat of opts.categories) {
    if (!hasCredentials) {
      result[cat.id] = [];
      continue;
    }
    try {
      const photos = await getCategoryImages(cat.id);
      result[cat.id] = photos;
      console.log(`[generate-image-data] [${opts.label}] ${cat.id}: ${photos.length} image(s)`);
    } catch (err) {
      console.warn(`[generate-image-data] [${opts.label}] Failed to fetch "${cat.id}" — using empty list:`, (err as Error).message);
      result[cat.id] = [];
    }
  }

  const fileContents =
    "// AUTO-GENERATED by scripts/generate-image-data.ts — do not edit by hand.\n" +
    "// Regenerated fresh on every `npm run dev` / `npm run build` from the\n" +
    "// current upload provider. Gitignored — see .gitignore.\n" +
    // Keyed by plain string, not the strict FurnitureCategoryId/
    // DoorsWindowsCategoryId union — the category list here includes
    // admin-created (dynamic) categories, which aren't (and can't be) part
    // of that compile-time union.
    `export interface CategoryPhoto {\n  secureUrl: string;\n  productCode: string;\n  createdAt: string;\n}\n\n` +
    `const ${opts.varName}: Record<string, CategoryPhoto[]> = ${JSON.stringify(result, null, 2)};\n\n` +
    `export default ${opts.varName};\n`;

  mkdirSync(path.dirname(opts.outPath), { recursive: true });
  writeFileSync(opts.outPath, fileContents);
  console.log(`[generate-image-data] [${opts.label}] Wrote ${opts.outPath}`);
}

// The generated file's arrays are already vertical-segregated (dynamicFurnitureCategories
// vs dynamicDoorsWindowsCategories), so the `vertical` field on each entry is redundant here.
function strip(categories: DynamicCategory[]): Array<Omit<DynamicCategory, "vertical">> {
  return categories.map(({ id, name, prefix, createdAt }) => ({ id, name, prefix, createdAt }));
}

function writeDynamicCategoriesFile(furniture: DynamicCategory[], doorsWindows: DynamicCategory[]): void {
  const outPath = path.resolve(__dirname, "../src/data/dynamicCategories.generated.ts");
  const fileContents =
    "// AUTO-GENERATED by scripts/generate-image-data.ts — do not edit by hand.\n" +
    "// Admin-created categories (see api-lib/dynamicCategories.ts), fetched fresh\n" +
    "// from Cloudinary on every build. Gitignored — see .gitignore.\n" +
    `export interface DynamicCategory {\n  id: string;\n  name: string;\n  prefix: string;\n  createdAt: string;\n}\n\n` +
    `export const dynamicFurnitureCategories: DynamicCategory[] = ${JSON.stringify(strip(furniture), null, 2)};\n\n` +
    `export const dynamicDoorsWindowsCategories: DynamicCategory[] = ${JSON.stringify(strip(doorsWindows), null, 2)};\n`;

  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, fileContents);
  console.log(`[generate-image-data] Wrote ${outPath} (${furniture.length} furniture, ${doorsWindows.length} doors-windows dynamic categories)`);
}

async function main() {
  if (!hasCredentials) {
    console.warn(
      "[generate-image-data] Cloudinary credentials not found — writing empty data files. " +
        "Set VITE_CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET to fetch real images.",
    );
  }

  let dynamicFurniture: DynamicCategory[] = [];
  let dynamicDW: DynamicCategory[] = [];
  if (hasCredentials) {
    try {
      [dynamicFurniture, dynamicDW] = await Promise.all([
        getDynamicCategories("furniture"),
        getDynamicCategories("doors-windows"),
      ]);
    } catch (err) {
      console.warn("[generate-image-data] Failed to fetch dynamic categories — treating as none:", (err as Error).message);
    }
  }
  writeDynamicCategoriesFile(dynamicFurniture, dynamicDW);

  await generate({
    label: "furniture",
    categories: [...furnitureCategories, ...dynamicFurniture],
    outPath: path.resolve(__dirname, "../src/data/categoryPhotos.generated.ts"),
    varName: "categoryPhotosByCategory",
  });

  await generate({
    label: "doors-windows",
    categories: [...doorsWindowsCategories, ...dynamicDW],
    outPath: path.resolve(__dirname, "../src/data/dwCategoryPhotos.generated.ts"),
    varName: "dwCategoryPhotosByCategory",
  });
}

main().catch((err) => {
  console.error("[generate-image-data] Fatal error:", err);
  process.exit(1);
});
