// Runs at build time (wired as `predev`/`prebuild` in package.json) — the
// ONLY thing that decides WHEN images get fetched. Calls getCategoryImages
// once per real category, for BOTH verticals, and writes the results to
// src/data/categoryPhotos.generated.ts (Furniture) and
// src/data/dwCategoryPhotos.generated.ts (Doors & Windows), which frontend
// pages import directly as plain static data.
//
// Resilient by design: a category the client hasn't uploaded to yet, a
// network hiccup, or missing credentials on a fresh local clone should
// never fail the whole build — they just produce an empty array for that
// category, and the existing hasValue/placeholder pattern takes it from
// there.
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getCategoryImages, type CategoryPhoto } from "./imageProvider.ts";
import { furnitureCategories } from "../shared/furnitureCategories.ts";
import { doorsWindowsCategories } from "../shared/doorsWindowsCategories.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const hasCredentials =
  !!process.env.VITE_CLOUDINARY_CLOUD_NAME &&
  !!process.env.CLOUDINARY_API_KEY &&
  !!process.env.CLOUDINARY_API_SECRET;

interface GenerateOptions {
  label: string; // for console logging only
  categories: readonly { id: string }[];
  outPath: string;
  categoryIdTypeImport: string; // e.g. `import type { FurnitureCategoryId } from "../../shared/furnitureCategories";`
  categoryIdType: string; // e.g. "FurnitureCategoryId"
  varName: string; // e.g. "categoryPhotosByCategory"
}

async function generate(opts: GenerateOptions): Promise<void> {
  const result: Record<string, CategoryPhoto[]> = {};

  for (const cat of opts.categories) {
    if (!hasCredentials) {
      result[cat.id] = [];
      continue;
    }
    try {
      const photos = await getCategoryImages(cat.id);
      result[cat.id] = photos;
      console.log(`[generate-image-data] [${opts.label}] ${cat.id}: ${photos.length} image(s)`);
    } catch (err) {
      console.warn(`[generate-image-data] [${opts.label}] Failed to fetch "${cat.id}" — using empty list:`, (err as Error).message);
      result[cat.id] = [];
    }
  }

  const fileContents =
    "// AUTO-GENERATED by scripts/generate-image-data.ts — do not edit by hand.\n" +
    "// Regenerated fresh on every `npm run dev` / `npm run build` from the\n" +
    "// current upload provider. Gitignored — see .gitignore.\n" +
    `${opts.categoryIdTypeImport}\n\n` +
    `export interface CategoryPhoto {\n  secureUrl: string;\n  productCode: string;\n  createdAt: string;\n}\n\n` +
    `const ${opts.varName}: Record<${opts.categoryIdType}, CategoryPhoto[]> = ${JSON.stringify(result, null, 2)};\n\n` +
    `export default ${opts.varName};\n`;

  mkdirSync(path.dirname(opts.outPath), { recursive: true });
  writeFileSync(opts.outPath, fileContents);
  console.log(`[generate-image-data] [${opts.label}] Wrote ${opts.outPath}`);
}

async function main() {
  if (!hasCredentials) {
    console.warn(
      "[generate-image-data] Cloudinary credentials not found — writing empty data files. " +
        "Set VITE_CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET to fetch real images.",
    );
  }

  await generate({
    label: "furniture",
    categories: furnitureCategories,
    outPath: path.resolve(__dirname, "../src/data/categoryPhotos.generated.ts"),
    categoryIdTypeImport: `import type { FurnitureCategoryId } from "../../shared/furnitureCategories";`,
    categoryIdType: "FurnitureCategoryId",
    varName: "categoryPhotosByCategory",
  });

  await generate({
    label: "doors-windows",
    categories: doorsWindowsCategories,
    outPath: path.resolve(__dirname, "../src/data/dwCategoryPhotos.generated.ts"),
    categoryIdTypeImport: `import type { DoorsWindowsCategoryId } from "../../shared/doorsWindowsCategories";`,
    categoryIdType: "DoorsWindowsCategoryId",
    varName: "dwCategoryPhotosByCategory",
  });
}

main().catch((err) => {
  console.error("[generate-image-data] Fatal error:", err);
  process.exit(1);
});
