// Runs at build time (wired as `predev`/`prebuild` in package.json) — the
// ONLY thing that decides WHEN images get fetched. Calls getCategoryImages
// once per real furniture category and writes the results to
// src/data/categoryPhotos.generated.ts, which frontend pages import
// directly as plain static data (see FurnitureCategoryPage.tsx).
//
// Resilient by design: a category the client hasn't uploaded to yet, a
// network hiccup, or missing credentials on a fresh local clone should
// never fail the whole build — they just produce an empty array for that
// category, and the existing hasValue/placeholder pattern takes it from
// there.
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getCategoryImages, type CategoryPhoto } from "./imageProvider.ts";
import { furnitureCategories } from "../shared/furnitureCategories.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, "../src/data/categoryPhotos.generated.ts");

async function main() {
  const hasCredentials =
    !!process.env.VITE_CLOUDINARY_CLOUD_NAME &&
    !!process.env.CLOUDINARY_API_KEY &&
    !!process.env.CLOUDINARY_API_SECRET;

  const result: Record<string, CategoryPhoto[]> = {};

  for (const cat of furnitureCategories) {
    if (!hasCredentials) {
      result[cat.id] = [];
      continue;
    }
    try {
      const photos = await getCategoryImages(cat.id);
      result[cat.id] = photos;
      console.log(`[generate-image-data] ${cat.id}: ${photos.length} image(s)`);
    } catch (err) {
      console.warn(`[generate-image-data] Failed to fetch "${cat.id}" — using empty list:`, (err as Error).message);
      result[cat.id] = [];
    }
  }

  if (!hasCredentials) {
    console.warn(
      "[generate-image-data] Cloudinary credentials not found — writing an empty data file. " +
        "Set VITE_CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET to fetch real images.",
    );
  }

  const fileContents =
    "// AUTO-GENERATED by scripts/generate-image-data.ts — do not edit by hand.\n" +
    "// Regenerated fresh on every `npm run dev` / `npm run build` from the\n" +
    "// current upload provider. Gitignored — see .gitignore.\n" +
    `import type { FurnitureCategoryId } from "../../shared/furnitureCategories";\n\n` +
    `export interface CategoryPhoto {\n  secureUrl: string;\n  productCode: string;\n}\n\n` +
    `const categoryPhotosByCategory: Record<FurnitureCategoryId, CategoryPhoto[]> = ${JSON.stringify(result, null, 2)};\n\n` +
    "export default categoryPhotosByCategory;\n";

  mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, fileContents);
  console.log(`[generate-image-data] Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error("[generate-image-data] Fatal error:", err);
  process.exit(1);
});
